version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: joda-time:joda-time
    versions:
    - "> 2.10.1"
  - dependency-name: org.apache.felix:maven-bundle-plugin
    versions:
    - ">= 4.2.a, < 4.3"
  - dependency-name: org.apache.hadoop:hadoop-client
    versions:
    - ">= 3.2.0.a, < 3.2.1"
  - dependency-name: org.apache.maven.plugins:maven-source-plugin
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: com.diffplug.spotless:spotless-maven-plugin
    versions:
    - 2.10.0
    - 2.10.1
    - 2.8.0
    - 2.8.1
    - 2.9.0
  - dependency-name: com.github.luben:zstd-jni
    versions:
    - 1.4.8-2
    - 1.4.8-3
    - 1.4.8-4
    - 1.4.8-5
    - 1.4.8-6
    - 1.4.8-7
    - 1.4.9-1
    - 1.4.9-2
    - 1.4.9-3
    - 1.4.9-4
  - dependency-name: com.google.protobuf:protobuf-java
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: io.netty:netty-bom
    versions:
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.apache.felix:maven-bundle-plugin
    versions:
    - 5.1.1
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
  - dependency-name: org.apache.maven:maven-compat
    versions:
    - 3.6.3
  - dependency-name: org.apache.maven:maven-core
    versions:
    - 3.6.3
  - dependency-name: io.grpc:grpc-netty
    versions:
    - 1.35.0
  - dependency-name: io.grpc:grpc-stub
    versions:
    - 1.35.0
  - dependency-name: io.grpc:grpc-core
    versions:
    - 1.35.0
  - dependency-name: org.apache.maven.plugins:maven-site-plugin
    versions:
    - 3.9.1
  - dependency-name: org.apache.hadoop:hadoop-client
    versions:
    - 3.3.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
